branch-defaults:
  master:
    environment: babyl-django-env
    group_suffix: null
environment-defaults:
  babyl-django-env:
    branch: null
    repository: null
  babylproject-dev:
    branch: null
    repository: null
global:
  application_name: babylproject
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
