# Generated by Django 2.2.1 on 2019-08-01 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20190801_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
