# Generated by Django 2.2.1 on 2019-08-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_slug',
            field=models.CharField(default='temp_slug', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
