# Generated by Django 2.2.1 on 2019-08-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20190801_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
