# Generated by Django 2.2.1 on 2019-08-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_slug',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
